language: node_js
node_js:
- '4.0'
- '9.0'
sudo: false
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: akSkN0mjd+4J3u0Vp7lHAne3I5OMN4O7/sXSH08GVqnnL3kIzVhweiwkRrQ/c8gV5eqMksAnroSoOAs/cPb3S2+QBcSjEMopjgZ+dbOdq45gbpCpwPefMT64dD7N0hGB00CwQzFRdiN41ubTR9FiQNRuRyHAavqA5krH5UHY1yw=
  file:
    - "levenshtein-edit-distance.js"
    - "levenshtein-edit-distance.min.js"
  on:
    tags: true
    node: '9.0'
